<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-HHODFUV" ignored="0" name="Default test" tests="6" failures="1" timestamp="2021-09-02T15:03:09 EDT" time="59.669" errors="0">
  <testcase name="loginWithWrong_1" time="2.489" classname="tests.FaceboolLogins"/>
  <testcase name="loginWithNoEmail_2" time="0.878" classname="tests.FaceboolLogins"/>
  <testcase name="loginWithNoPass_3" time="1.857" classname="tests.FaceboolLogins"/>
  <testcase name="loginWithInvalidEmail_4" time="2.016" classname="tests.FaceboolLogins"/>
  <testcase name="wrongNumber_5" time="1.804" classname="tests.FaceboolLogins"/>
  <testcase name="emailNoAccount_6" time="0.75" classname="tests.FaceboolLogins">
    <failure type="org.junit.ComparisonFailure" message="expected:&amp;lt;...ected to an account.[]&amp;gt; but was:&amp;lt;...ected to an account.[ Find your account and log in.]&amp;gt;">
      <![CDATA[org.junit.ComparisonFailure: expected:<...ected to an account.[]> but was:<...ected to an account.[ Find your account and log in.]>
at org.junit.Assert.assertEquals(Assert.java:115)
at org.junit.Assert.assertEquals(Assert.java:144)
at tests.FaceboolLogins.emailNoAccount_6(FaceboolLogins.java:77)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- emailNoAccount_6 -->
</testsuite> <!-- Default test -->
